# Generated by Django 4.2.4 on 2023-12-23 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_remove_category_categories'),
        ('task', '0002_taskmodel_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskmodel',
            name='categories',
            field=models.ManyToManyField(to='category.category'),
        ),
    ]
